services:
  - type: web
    name: galina-potekhina
    runtime: node
    plan: free
    buildCommand: git lfs install && git lfs pull && npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: SITE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_LOGIN
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
